name: packages
description: "Mock packages for POS System"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  flutter_blue_plus:
    git:
      url: https://github.com/chipweinberger/flutter_blue_plus
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  mockito: ^5.4.4

flutter:
